{
  "openapi": "3.0.0",
  "info": {
    "title": "EU SDX-Engine",
    "description": "SdxEngine for operations on sodex system data. Usage guide: https://sdx-software.atlassian.net/l/cp/m9rtU1tr",
    "version": "2.0.0"
  },
  "servers": [
    {
      "url": "https://api.sodex.cloud/v2"
    }
  ],
  "paths": {
    "/calendar-settings/": {
      "get": {
        "tags": ["CalendarSettings"],
        "summary": "Get all calendar_settings - Sodex only",
        "description": "Get all calendar_settings",
        "operationId": "get_all_calendar_settings_calendar_settings__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/calendar-settings/{calendar_settings_id}": {
      "get": {
        "tags": ["CalendarSettings"],
        "summary": "Get calendar_setting by id",
        "description": "Get calendar_setting by id",
        "operationId": "get_calendar_setting_by_id_calendar_settings__calendar_settings_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["CalendarSettings"],
        "summary": "Update calendar_setting",
        "description": "Update calendar_setting",
        "operationId": "update_calendar_setting_calendar_settings__calendar_settings_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "delete": {
        "tags": ["CalendarSettings"],
        "summary": "Delete calendar_setting",
        "description": "Delete calendar_setting",
        "operationId": "delete_calendar_setting_calendar_settings__calendar_settings_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/project/{project_id}/calendar-settings": {
      "get": {
        "tags": ["CalendarSettings"],
        "summary": "Get all calendar_settings for a project",
        "description": "Get all calendar_settings for a project",
        "operationId": "get_all_calendar_settings_for_project_project__project_id__calendar_settings_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/calendar/{calendar_id}/settings": {
      "get": {
        "tags": ["CalendarSettings"],
        "summary": "Get user calendar settings",
        "description": "Get all callendar settings for a calendar for this user",
        "operationId": "get_all_calendar_settings_for_calendar_calendar__calendar_id__settings_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/calendar-events/": {
      "get": {
        "tags": ["CalendarEvents"],
        "summary": "Get all calendar_events - Sodex only",
        "description": "Get all calendar_events",
        "operationId": "get_all_calendar_events_calendar_events__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/calendar-events/{calendar_event_id}": {
      "get": {
        "tags": ["CalendarEvents"],
        "summary": "Get calendar_event by id",
        "description": "Get calendar_event by id",
        "operationId": "get_calendar_event_by_id_calendar_events__calendar_event_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["CalendarEvents"],
        "summary": "Update calendar_event",
        "description": "Update calendar_event",
        "operationId": "update_calendar_event_calendar_events__calendar_event_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      },
      "delete": {
        "tags": ["CalendarEvents"],
        "summary": "Delete calendar_event",
        "description": "Delete calendar_event",
        "operationId": "delete_calendar_event_calendar_events__calendar_event_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/projects/{project_id}/calendar-events": {
      "get": {
        "tags": ["CalendarEvents"],
        "summary": "Get all calendar_events for a project",
        "description": "Get all calendar_events for a project",
        "operationId": "get_all_calendar_events_for_project_projects__project_id__calendar_events_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/calendar/{calendar_id}/events": {
      "get": {
        "tags": ["CalendarEvents"],
        "summary": "Get all calendar_events for a calendar",
        "description": "Get all calendar_events for a calendar",
        "operationId": "get_all_calendar_events_for_calendar_calendar__calendar_id__events_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/calendar/{calendar_id}/event": {
      "post": {
        "tags": ["CalendarEvents"],
        "summary": "Create new calendar event",
        "description": "Create new calendar event",
        "operationId": "create_calendar_event_calendar__calendar_id__event_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/calendar-events/{calendar_event_id}/files": {
      "put": {
        "tags": ["CalendarEvents"],
        "summary": "Update calendar_event files",
        "description": "Update calendar_event files",
        "operationId": "update_calendar_event_files_calendar_events__calendar_event_id__files_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/calendars/": {
      "get": {
        "tags": ["Calendars"],
        "summary": "Get all calendars - Sodex only",
        "description": "Get all calendars",
        "operationId": "get_all_calendars_calendars__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/calendars/{calendar_id}": {
      "get": {
        "tags": ["Calendars"],
        "summary": "Get calendar by id",
        "description": "Get calendar by id",
        "operationId": "get_calendar_by_id_calendars__calendar_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["Calendars"],
        "summary": "Update calendar",
        "description": "Update calendar",
        "operationId": "update_calendar_calendars__calendar_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "delete": {
        "tags": ["Calendars"],
        "summary": "Delete calendar",
        "description": "Delete calendar",
        "operationId": "delete_calendar_calendars__calendar_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/calendars": {
      "get": {
        "tags": ["Calendars"],
        "summary": "Get project calendars",
        "description": "Get project calendars",
        "operationId": "get_project_calendars_projects__project_id__calendars_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Calendars"],
        "summary": "Create new calendar for a project",
        "description": "Create new calendar for a project",
        "operationId": "create_calendar_for_project_projects__project_id__calendars_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/calendars-with-settings": {
      "get": {
        "tags": ["Calendars"],
        "summary": "Get project calendars with settings",
        "description": "Get project calendars with settings",
        "operationId": "get_project_calendars_with_settings_projects__project_id__calendars_with_settings_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/notifications/": {
      "get": {
        "tags": ["Notifications"],
        "summary": "Get all notifications - Sodex only",
        "description": "Get all notifications",
        "operationId": "get_all_notifications_notifications__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/notifications/{notification_id}": {
      "get": {
        "tags": ["Notifications"],
        "summary": "Get notification by id",
        "description": "Get notification by id",
        "operationId": "get_notification_by_id_notifications__notification_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Notifications"],
        "summary": "Update notification",
        "description": "Update notification",
        "operationId": "update_notification_notifications__notification_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Notifications"],
        "summary": "Delete notification",
        "description": "Delete notification",
        "operationId": "delete_notification_notifications__notification_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/users/me/notifications/": {
      "get": {
        "tags": ["Notifications"],
        "summary": "Get all notifications",
        "description": "Get all notifications",
        "operationId": "get_all_notifications_users_me_notifications__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/users/me/notifications/clear-all": {
      "put": {
        "tags": ["Notifications"],
        "summary": "Clear all notifications",
        "description": "Clear all notifications",
        "operationId": "clear_all_notifications_users_me_notifications_clear_all_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/notification-settings/": {
      "get": {
        "tags": ["NotificationSettings"],
        "summary": "Get all notification_settings - Sodex only",
        "description": "Get all notification_settings",
        "operationId": "get_all_notification_settings_notification_settings__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/notification-settings/{notification_settings_id}": {
      "get": {
        "tags": ["NotificationSettings"],
        "summary": "Get notification_setting by id",
        "description": "Get notification_setting by id",
        "operationId": "get_notification_setting_by_id_notification_settings__notification_settings_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["NotificationSettings"],
        "summary": "Update notification_setting",
        "description": "Update notification_setting",
        "operationId": "update_notification_setting_notification_settings__notification_settings_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["NotificationSettings"],
        "summary": "Delete notification_setting",
        "description": "Delete notification_setting",
        "operationId": "delete_notification_setting_notification_settings__notification_settings_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/users/me/notification-settings": {
      "get": {
        "tags": ["NotificationSettings"],
        "summary": "Get notification_setting by user id",
        "description": "Get notification_setting by user id",
        "operationId": "get_notification_settings_of_my_user_users_me_notification_settings_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["NotificationSettings"],
        "summary": "Update notification_setting by user id",
        "description": "Update notification_setting by user id",
        "operationId": "update_notification_settings_of_my_user_users_me_notification_settings_put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["NotificationSettings"],
        "summary": "Create notification_setting by user id",
        "description": "Create notification_setting by user id",
        "operationId": "create_notification_settings_of_my_user_users_me_notification_settings_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-segments/": {
      "get": {
        "tags": ["CableSegments"],
        "summary": "Get all segments - Sodex only",
        "description": "Get all segments",
        "operationId": "get_all_segments_cable_segments__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cable-segments/{cable_segment_id}": {
      "get": {
        "tags": ["CableSegments"],
        "summary": "Get segment by id",
        "description": "Get segment by id",
        "operationId": "get_segment_by_id_cable_segments__cable_segment_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["CableSegments"],
        "summary": "Update segment",
        "description": "Update segment",
        "operationId": "update_segment_cable_segments__cable_segment_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CableSegments"],
        "summary": "Delete segment",
        "description": "Delete segment",
        "operationId": "delete_segment_cable_segments__cable_segment_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/cable-segments": {
      "get": {
        "tags": ["CableSegments"],
        "summary": "Get all segments for a project",
        "description": "Get all segments for a project",
        "operationId": "get_all_segments_for_project_projects__project_id__cable_segments_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cables/{cable_id}/segments": {
      "get": {
        "tags": ["CableSegments"],
        "summary": "Get all segments for a cable",
        "description": "Get all segments for a cable",
        "operationId": "get_all_segments_for_cable_cables__cable_id__segments_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/cable/{cable_id}/segments": {
      "post": {
        "tags": ["CableSegments"],
        "summary": "Create segment for my system and cable",
        "description": "Create segment for my system and cable",
        "operationId": "create_segment_for_my_system_and_cable_systems_me_cable__cable_id__segments_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/cable/{cable_id}/segments": {
      "post": {
        "tags": ["CableSegments"],
        "summary": "Create segment for a system and cable",
        "description": "Create segment for a system and cable",
        "operationId": "create_segment_for_system_and_cable_systems__system_id__cable__cable_id__segments_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable/{cable_id}/segments": {
      "post": {
        "tags": ["CableSegments"],
        "summary": "Create segment for a cable",
        "description": "Create segment for a cable",
        "operationId": "create_segment_for_cable_cable__cable_id__segments_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-segments/{cable_segment_id}/file-count": {
      "get": {
        "tags": ["CableSegments"],
        "summary": "Get segment file count",
        "description": "Get segment file count",
        "operationId": "get_segment_file_count_cable_segments__cable_segment_id__file_count_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-block-areas/": {
      "get": {
        "tags": ["CableBlockAreas"],
        "summary": "Get all cable_block_areas - Sodex only",
        "description": "Get all cable_block_areas",
        "operationId": "get_all_cable_block_areas_cable_block_areas__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cable-block-areas/{cable_block_area_id}": {
      "get": {
        "tags": ["CableBlockAreas"],
        "summary": "Get cable_block_area by id",
        "description": "Get cable_block_area by id",
        "operationId": "get_cable_block_area_by_id_cable_block_areas__cable_block_area_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["CableBlockAreas"],
        "summary": "Update cable_block_area",
        "description": "Update cable_block_area",
        "operationId": "update_cable_block_area_cable_block_areas__cable_block_area_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CableBlockAreas"],
        "summary": "Delete cable_block_area",
        "description": "Delete cable_block_area",
        "operationId": "delete_cable_block_area_cable_block_areas__cable_block_area_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/cable-block-areas": {
      "get": {
        "tags": ["CableBlockAreas"],
        "summary": "Get all cable_block_areas for a project",
        "description": "Get all cable_block_areas for a project",
        "operationId": "get_all_cable_block_areas_for_project_projects__project_id__cable_block_areas_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["CableBlockAreas"],
        "summary": "Create new cable_block_area for a project",
        "description": "Create new cable_block_area for a project",
        "operationId": "create_cable_block_area_for_project_projects__project_id__cable_block_areas_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-points/": {
      "get": {
        "tags": ["CablePoints"],
        "summary": "Get all cable_points - Sodex only",
        "description": "Get all cable_points",
        "operationId": "get_all_cable_points_cable_points__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cable-points/{cable_point_id}": {
      "get": {
        "tags": ["CablePoints"],
        "summary": "Get cable_point by id",
        "description": "Get cable_point by id",
        "operationId": "get_cable_point_by_id_cable_points__cable_point_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["CablePoints"],
        "summary": "Update cable_point",
        "description": "Update cable_point",
        "operationId": "update_cable_point_cable_points__cable_point_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CablePoints"],
        "summary": "Delete cable_point",
        "description": "Delete cable_point",
        "operationId": "delete_cable_point_cable_points__cable_point_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/cable-points": {
      "get": {
        "tags": ["CablePoints"],
        "summary": "Get all cable_points for a project",
        "description": "Get all cable_points for a project",
        "operationId": "get_all_cable_points_for_project_projects__project_id__cable_points_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cables/{cable_id}/points": {
      "get": {
        "tags": ["CablePoints"],
        "summary": "Get all cable_points for a cable",
        "description": "Get all cable_points for a cable",
        "operationId": "get_all_cable_points_for_cable_cables__cable_id__points_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-segments/{cable_segment_id}/points": {
      "get": {
        "tags": ["CablePoints"],
        "summary": "Get all cable_points for a cable_segment",
        "description": "Get all cable_points for a cable_segment",
        "operationId": "get_all_cable_points_for_segment_cable_segments__cable_segment_id__points_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["CablePoints"],
        "summary": "Create points for cable segment",
        "description": "Create points for a cable segment",
        "operationId": "create_cable_points_for_segment_cable_segments__cable_segment_id__points_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-segments/{cable_segment_id}/point": {
      "post": {
        "tags": ["CablePoints"],
        "summary": "Create point for cable segment",
        "description": "Create point for a cable segment",
        "operationId": "create_cable_point_for_segment_cable_segments__cable_segment_id__point_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cables/{cable_id}/points-import": {
      "post": {
        "tags": ["CablePoints"],
        "summary": "Import points for cable-segment",
        "description": "Import points for a cable-segment",
        "operationId": "import_cable_segment_points_cables__cable_id__points_import_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-points/many": {
      "put": {
        "tags": ["CablePoints"],
        "summary": "Update many cable_points",
        "description": "Update many cable_points",
        "operationId": "update_many_cable_points_cable_points_many_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/cable-points/{cable_point_id}/file": {
      "post": {
        "tags": ["CablePoints"],
        "summary": "Upload files to cable point",
        "description": "Upload files to cable point",
        "operationId": "upload_file_to_cable_point_cable_points__cable_point_id__file_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-points/{cable_point_id}/files": {
      "get": {
        "tags": ["CablePoints"],
        "summary": "Get files from cable point",
        "description": "Get files from cable point",
        "operationId": "get_files_from_cable_point_cable_points__cable_point_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CablePoints"],
        "summary": "Delete all files from cable point",
        "description": "Delete all files from cable point",
        "operationId": "delete_files_from_cable_point_cable_points__cable_point_id__files_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-points/{cable_point_id}/files/{file_id}": {
      "delete": {
        "tags": ["CablePoints"],
        "summary": "Delete file from cable point",
        "description": "Delete file from cable point",
        "operationId": "delete_file_from_cable_point_cable_points__cable_point_id__files__file_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cables/": {
      "get": {
        "tags": ["Cables"],
        "summary": "Get all cables - Sodex only",
        "description": "Get all cables",
        "operationId": "get_all_cables_cables__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cables/{cable_id}": {
      "get": {
        "tags": ["Cables"],
        "summary": "Get cable by id",
        "description": "Get cable by id",
        "operationId": "get_cable_by_id_cables__cable_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Cables"],
        "summary": "Update cable",
        "description": "Update cable",
        "operationId": "update_cable_cables__cable_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Cables"],
        "summary": "Delete cable",
        "description": "Delete cable",
        "operationId": "delete_cable_cables__cable_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/cables": {
      "get": {
        "tags": ["Cables"],
        "summary": "Get all cables of project",
        "description": "Get all cables of project",
        "operationId": "get_all_cables_for_project_projects__project_id__cables_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/layers/{cable_layer_id}/cables": {
      "get": {
        "tags": ["Cables"],
        "summary": "Get all cables of cablelayer",
        "description": "Get all cables of cablelayer",
        "operationId": "get_all_cables_for_layer_layers__cable_layer_id__cables_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Cables"],
        "summary": "Create new cable for a layer",
        "description": "Create new cable for a layer",
        "operationId": "create_cable_for_project_layers__cable_layer_id__cables_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cables/{cable_id}/file-count": {
      "get": {
        "tags": ["Cables"],
        "summary": "Get cable file count",
        "description": "Get cable file count",
        "operationId": "get_cable_file_count_cables__cable_id__file_count_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-types/": {
      "get": {
        "tags": ["CableTypes"],
        "summary": "Get all cable_types - Sodex only",
        "description": "Get all cable_types",
        "operationId": "get_all_cable_types_cable_types__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cable-types/{cable_type_id}": {
      "get": {
        "tags": ["CableTypes"],
        "summary": "Get cable_type by id",
        "description": "Get cable_type by id",
        "operationId": "get_cable_type_by_id_cable_types__cable_type_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["CableTypes"],
        "summary": "Update cable_type",
        "description": "Update cable_type",
        "operationId": "update_cable_type_cable_types__cable_type_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CableTypes"],
        "summary": "Delete cable_type",
        "description": "Delete cable_type",
        "operationId": "delete_cable_type_cable_types__cable_type_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/me/cable-types": {
      "get": {
        "tags": ["CableTypes"],
        "summary": "Get all cable_types of my organization",
        "description": "Get all cable_types of my organization",
        "operationId": "get_all_cable_types_of_my_organization_organizations_me_cable_types_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["CableTypes"],
        "summary": "Create new cable_type",
        "description": "Create new cable_type",
        "operationId": "create_cable_type_organizations_me_cable_types_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-layers/": {
      "get": {
        "tags": ["CableLayers"],
        "summary": "Get all cable_layers - Sodex only",
        "description": "Get all cable_layers",
        "operationId": "get_all_cable_layers_cable_layers__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cable-layers/{cable_layer_id}": {
      "get": {
        "tags": ["CableLayers"],
        "summary": "Get cable_layer by id",
        "description": "Get cable_layer by id",
        "operationId": "get_cable_layer_by_id_cable_layers__cable_layer_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["CableLayers"],
        "summary": "Update cable_layer",
        "description": "Update cable_layer",
        "operationId": "update_cable_layer_cable_layers__cable_layer_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CableLayers"],
        "summary": "Delete cable_layer",
        "description": "Delete cable_layer",
        "operationId": "delete_cable_layer_cable_layers__cable_layer_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/cable-layers": {
      "get": {
        "tags": ["CableLayers"],
        "summary": "Get all cable_layers for a project",
        "description": "Get all cable_layers for a project",
        "operationId": "get_all_cable_layers_for_project_projects__project_id__cable_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["CableLayers"],
        "summary": "Create new cable_layer for a project",
        "description": "Create new cable_layer for a project",
        "operationId": "create_cable_layer_for_project_projects__project_id__cable_layers_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-layers/{cable_layer_id}/file-count": {
      "get": {
        "tags": ["CableLayers"],
        "summary": "Get cable layer file count",
        "description": "Get cable layer file count",
        "operationId": "get_cable_layer_file_count_cable_layers__cable_layer_id__file_count_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshots/{snapshot_id}/file-count-cables": {
      "get": {
        "tags": ["CableLayers"],
        "summary": "Get snapshot file count for cables",
        "description": "Get snapshot file count for cables",
        "operationId": "get_snapshot_file_count_cables_snapshots__snapshot_id__file_count_cables_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-point-links/": {
      "get": {
        "tags": ["CablePointLinks"],
        "summary": "Get all point_links - Sodex only",
        "description": "Get all point_links",
        "operationId": "get_all_cable_point_links_cable_point_links__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/cable-point-links": {
      "get": {
        "tags": ["CablePointLinks"],
        "summary": "Get all point_links for a project",
        "description": "Get all point_links for a project",
        "operationId": "get_all_cable_point_links_for_project_projects__project_id__cable_point_links_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cable-point-link/{cable_point_link_id}": {
      "get": {
        "tags": ["CablePointLinks"],
        "summary": "Get cable point link by id",
        "description": "Get cable point link by id",
        "operationId": "get_cable_point_link_by_id_cable_point_link__cable_point_link_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["CablePointLinks"],
        "summary": "Update cable point link",
        "description": "Update cable point link",
        "operationId": "update_cable_point_link_cable_point_link__cable_point_link_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "delete": {
        "tags": ["CablePointLinks"],
        "summary": "Delete cable point link",
        "description": "Delete cable point link",
        "operationId": "delete_cable_point_link_cable_point_link__cable_point_link_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/cable-points/link": {
      "post": {
        "tags": ["CablePointLinks"],
        "summary": "Create cable point link",
        "description": "Create cable point link",
        "operationId": "create_cable_point_link_by_points_cable_points_link_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/potrees/": {
      "get": {
        "tags": ["Potree"],
        "summary": "Get all potrees - Sodex only",
        "description": "Get all potrees",
        "operationId": "get_all_potrees_potrees__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/potrees/{potree_id}": {
      "get": {
        "tags": ["Potree"],
        "summary": "Get potree by id",
        "description": "Get potree by id",
        "operationId": "get_potree_by_id_potrees__potree_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Potree"],
        "summary": "Update potree",
        "description": "Update potree",
        "operationId": "update_potree_potrees__potree_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Potree"],
        "summary": "Delete potree",
        "description": "Delete potree",
        "operationId": "delete_potree_potrees__potree_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/potrees": {
      "get": {
        "tags": ["Potree"],
        "summary": "Get all potrees of a project",
        "description": "Get all potrees of a project",
        "operationId": "read_project_potrees_projects__project_id__potrees_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Potree"],
        "summary": "Create new potree",
        "description": "Create new potree",
        "operationId": "create_potree_projects__project_id__potrees_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/potrees/{potree_id}/share": {
      "post": {
        "tags": ["Potree"],
        "summary": "Create potree share token",
        "description": "Create a share token for a given potree",
        "operationId": "create_potree_share_token_potrees__potree_id__share_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshot-notes/": {
      "get": {
        "tags": ["Snapshot Notes"],
        "summary": "Get all snapshotnotes - Sodex only",
        "description": "Get all snapshotnotes",
        "operationId": "get_all_snapshotnotes_snapshot_notes__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/snapshot/{snapshot_id}/notes": {
      "get": {
        "tags": ["Snapshot Notes"],
        "summary": "Get all snapshotnotes for a snapshot",
        "description": "Get all snapshotnotes for a snapshot",
        "operationId": "get_all_snapshotnotes_by_snapshot_snapshot__snapshot_id__notes_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshots/{snapshot_id}/notes": {
      "post": {
        "tags": ["Snapshot Notes"],
        "summary": "Create snapshotnote",
        "description": "Create snapshotnote",
        "operationId": "create_snapshotnote_snapshots__snapshot_id__notes_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshot-notes/{snapshotnote_id}": {
      "put": {
        "tags": ["Snapshot Notes"],
        "summary": "Update snapshotnote",
        "description": "Update snapshotnote",
        "operationId": "update_snapshotnote_snapshot_notes__snapshotnote_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Snapshot Notes"],
        "summary": "Delete snapshotnote",
        "description": "Delete snapshotnote",
        "operationId": "delete_snapshotnote_snapshot_notes__snapshotnote_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/gallery/info": {
      "get": {
        "tags": ["Gallery"],
        "summary": "Get gallery info for project",
        "description": "Get gallery info for project",
        "operationId": "get_gallery_info_projects__project_id__gallery_info_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/gallery/date-info": {
      "get": {
        "tags": ["Gallery"],
        "summary": "Get gallery date info for project",
        "description": "Get gallery date info for project",
        "operationId": "get_gallery_date_info_projects__project_id__gallery_date_info_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/pins/{pin_id}/gallery/image": {
      "get": {
        "tags": ["Gallery"],
        "summary": "Get Gallery Image",
        "operationId": "get_gallery_image_pins__pin_id__gallery_image_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/filetypes/": {
      "get": {
        "tags": ["Filetypes"],
        "summary": "Get all filetypes",
        "description": "Get all filetypes",
        "operationId": "get_all_filetypes_filetypes__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      },
      "post": {
        "tags": ["Filetypes"],
        "summary": "Create new filetype",
        "description": "Create new filetype",
        "operationId": "create_filetype_filetypes__post",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/filetypes/snapshot": {
      "get": {
        "tags": ["Filetypes"],
        "summary": "Get all filetypes for snapshot download",
        "description": "Get all filetypes that can be used for snapshot download",
        "operationId": "get_all_filetypes_snapshot_filetypes_snapshot_get"
      }
    },
    "/filetypes/{filetype_id}": {
      "get": {
        "tags": ["Filetypes"],
        "summary": "Get filetype by id",
        "description": "Get filetype by id",
        "operationId": "get_filetype_by_id_filetypes__filetype_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Filetypes"],
        "summary": "Update filetype",
        "description": "Update filetype",
        "operationId": "update_filetype_filetypes__filetype_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Filetypes"],
        "summary": "Delete filetype",
        "description": "Delete filetype",
        "operationId": "delete_filetype_filetypes__filetype_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/states/": {
      "get": {
        "tags": ["States"],
        "summary": "Get all states",
        "description": "Get all states",
        "operationId": "get_all_states_states__get"
      },
      "post": {
        "tags": ["States"],
        "summary": "Create new state",
        "description": "Create new state",
        "operationId": "create_state_states__post",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/states/{state_id}": {
      "get": {
        "tags": ["States"],
        "summary": "Get state by id",
        "description": "Get state by id",
        "operationId": "get_state_by_id_states__state_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["States"],
        "summary": "Update state",
        "description": "Update state",
        "operationId": "update_state_states__state_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/state/phases": {
      "get": {
        "tags": ["States"],
        "summary": "Get state with phases by project id",
        "description": "Get state with phases by project id",
        "operationId": "get_state_by_project_id_projects__project_id__state_phases_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/gradients/": {
      "get": {
        "tags": ["Gradients"],
        "summary": "Get all gradients - Sodex only",
        "description": "Get all gradients",
        "operationId": "get_all_gradients_gradients__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/gradients/default": {
      "get": {
        "tags": ["Gradients"],
        "summary": "Get default gradients",
        "description": "Get default gradients",
        "operationId": "get_default_gradients_gradients_default_get"
      }
    },
    "/gradients/me": {
      "get": {
        "tags": ["Gradients"],
        "summary": "Get user gradients",
        "description": "Get user gradients",
        "operationId": "get_user_gradients_gradients_me_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["user"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/gradients/{gradient_id}": {
      "get": {
        "tags": ["Gradients"],
        "summary": "Get gradient by id",
        "description": "Get gradient by id",
        "operationId": "get_gradient_by_id_gradients__gradient_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Gradients"],
        "summary": "Update gradient",
        "description": "Update gradient",
        "operationId": "update_gradient_gradients__gradient_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Gradients"],
        "summary": "Delete gradient",
        "description": "Delete gradient",
        "operationId": "delete_gradient_gradients__gradient_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/gradients": {
      "post": {
        "tags": ["Gradients"],
        "summary": "Create new gradient",
        "description": "Create new gradient",
        "operationId": "create_gradient_gradients_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/buckets/": {
      "get": {
        "tags": ["Buckets"],
        "summary": "Get all buckets - Sodex only",
        "description": "Get all buckets",
        "operationId": "get_all_buckets_buckets__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/buckets/{bucket_id}": {
      "get": {
        "tags": ["Buckets"],
        "summary": "Get bucket by id",
        "description": "Get bucket by id",
        "operationId": "get_bucket_by_id_buckets__bucket_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Buckets"],
        "summary": "Update bucket",
        "description": "Update bucket",
        "operationId": "update_bucket_buckets__bucket_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Buckets"],
        "summary": "Delete bucket",
        "description": "Delete bucket",
        "operationId": "delete_bucket_buckets__bucket_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/buckets": {
      "get": {
        "tags": ["Buckets"],
        "summary": "Get my system buckets",
        "description": "Get my system buckets",
        "operationId": "get_my_system_buckets_systems_me_buckets_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Buckets"],
        "summary": "Create my system bucket",
        "description": "Create my system bucket",
        "operationId": "create_my_system_bucket_systems_me_buckets_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/buckets": {
      "get": {
        "tags": ["Buckets"],
        "summary": "Get system buckets",
        "description": "Get system buckets",
        "operationId": "get_system_buckets_systems__system_id__buckets_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "post": {
        "tags": ["Buckets"],
        "summary": "Create system bucket",
        "description": "Create system bucket",
        "operationId": "create_system_bucket_systems__system_id__buckets_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/profiles/": {
      "get": {
        "tags": ["Profiles"],
        "summary": "Get all profiles - Sodex only",
        "description": "Get all profiles",
        "operationId": "get_all_profiles_profiles__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/profiles/{systemprofile_id}": {
      "get": {
        "tags": ["Profiles"],
        "summary": "Get profile by id",
        "description": "Get profile by id",
        "operationId": "get_profile_by_id_profiles__systemprofile_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Profiles"],
        "summary": "Update profile",
        "description": "Update profile",
        "operationId": "update_profile_profiles__systemprofile_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Profiles"],
        "summary": "Delete profile",
        "description": "Delete profile",
        "operationId": "delete_profile_profiles__systemprofile_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/profiles": {
      "get": {
        "tags": ["Profiles"],
        "summary": "Get all profiles of current system",
        "description": "Get all profiles of current system",
        "operationId": "get_all_profiles_of_current_system_systems_me_profiles_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Profiles"],
        "summary": "Create profile for current system",
        "description": "Create profile for current system",
        "operationId": "create_profile_for_current_system_systems_me_profiles_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/profiles": {
      "get": {
        "tags": ["Profiles"],
        "summary": "Get all profiles of system",
        "description": "Get all profiles of system",
        "operationId": "get_all_profiles_of_system_systems__system_id__profiles_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          }
        ]
      },
      "post": {
        "tags": ["Profiles"],
        "summary": "Create profile",
        "description": "Create profile",
        "operationId": "create_profile_systems__system_id__profiles_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/quicktasks/": {
      "get": {
        "tags": ["Quick Tasks"],
        "summary": "Get all quicktasks - Sodex only",
        "description": "Get all quicktasks",
        "operationId": "get_all_quicktasks_quicktasks__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/quicktasks/{quicktask_id}": {
      "get": {
        "tags": ["Quick Tasks"],
        "summary": "Get quicktask by id",
        "description": "Get quicktask by id",
        "operationId": "get_quicktask_by_id_quicktasks__quicktask_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Quick Tasks"],
        "summary": "Update quicktask",
        "description": "Update quicktask",
        "operationId": "update_quicktask_quicktasks__quicktask_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Quick Tasks"],
        "summary": "Delete quicktask",
        "description": "Delete quicktask",
        "operationId": "delete_quicktask_quicktasks__quicktask_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/quicktasks": {
      "get": {
        "tags": ["Quick Tasks"],
        "summary": "Get all quicktasks of current system",
        "description": "Get all quicktasks of current system",
        "operationId": "get_all_quicktasks_of_current_system_systems_me_quicktasks_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/quicktasks": {
      "get": {
        "tags": ["Quick Tasks"],
        "summary": "Get all quicktasks of system",
        "description": "Get all quicktasks of system",
        "operationId": "get_all_quicktasks_of_system_systems__system_id__quicktasks_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          }
        ]
      },
      "post": {
        "tags": ["Quick Tasks"],
        "summary": "Create new quicktask",
        "description": "Create new quicktask",
        "operationId": "create_quicktask_systems__system_id__quicktasks_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/quicktasks/{quicktask_id}/files": {
      "get": {
        "tags": ["Quick Tasks"],
        "summary": "Get all files of quicktask with signed urls",
        "description": "Get all files of quicktask with signed urls",
        "operationId": "get_all_files_of_quicktask_quicktasks__quicktask_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Quick Tasks"],
        "summary": "Add files to quicktask",
        "description": "Add files to quicktask",
        "operationId": "add_files_to_quicktask_quicktasks__quicktask_id__files_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/quicktasks/{quicktask_id}/files/{s3_key}": {
      "delete": {
        "tags": ["Quick Tasks"],
        "summary": "Delete file of quicktask",
        "description": "Delete file of quicktask",
        "operationId": "delete_file_of_quicktask_quicktasks__quicktask_id__files__s3_key__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/merged-layers/": {
      "get": {
        "tags": ["Mergedlayers"],
        "summary": "Get all merged_layers - Sodex only",
        "description": "Get all merged_layers",
        "operationId": "get_all_merged_layers_merged_layers__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/merged-layers/{merged_layer_id}": {
      "get": {
        "tags": ["Mergedlayers"],
        "summary": "Get merged_layer by id",
        "description": "Get merged_layer by id",
        "operationId": "get_merged_layer_by_id_merged_layers__merged_layer_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Mergedlayers"],
        "summary": "Update merged_layer",
        "description": "Update merged_layer",
        "operationId": "update_merged_layer_merged_layers__merged_layer_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Mergedlayers"],
        "summary": "Delete merged_layer",
        "description": "Delete merged_layer",
        "operationId": "delete_merged_layer_merged_layers__merged_layer_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/merged-layers": {
      "get": {
        "tags": ["Mergedlayers"],
        "summary": "Get all merged_layers for a project",
        "description": "Get all merged_layers for a project",
        "operationId": "get_all_merged_layers_for_project_projects__project_id__merged_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Mergedlayers"],
        "summary": "Create new merged_layer for a project",
        "description": "Create new merged_layer for a project",
        "operationId": "create_merged_layer_for_project_projects__project_id__merged_layers_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/project-folders/": {
      "get": {
        "tags": ["Projectfolders"],
        "summary": "Get all project_folders - Sodex only",
        "description": "Get all project_folders",
        "operationId": "get_all_project_folders_project_folders__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/project-folders/{project_folder_id}": {
      "get": {
        "tags": ["Projectfolders"],
        "summary": "Get project_folder by id",
        "description": "Get project_folder by id",
        "operationId": "get_project_folder_by_id_project_folders__project_folder_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Projectfolders"],
        "summary": "Update project_folder",
        "description": "Update project_folder",
        "operationId": "update_project_folder_project_folders__project_folder_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Projectfolders"],
        "summary": "Delete project_folder",
        "description": "Delete project_folder",
        "operationId": "delete_project_folder_project_folders__project_folder_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/project-folders/{project_folder_id}/children": {
      "get": {
        "tags": ["Projectfolders"],
        "summary": "Get children project_folders by id",
        "description": "Get children project_folders by id",
        "operationId": "get_children_project_folders_by_id_project_folders__project_folder_id__children_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Projectfolders"],
        "summary": "Create a child project_folder",
        "description": "Create a child project_folder",
        "operationId": "create_child_project_folder_project_folders__project_folder_id__children_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organization/me/project-folders/root": {
      "get": {
        "tags": ["Projectfolders"],
        "summary": "Get root project_folder for my organization",
        "description": "Get root project_folder for my organization",
        "operationId": "get_root_project_folder_for_my_organization_organization_me_project_folders_root_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organization/me/project-folders": {
      "get": {
        "tags": ["Projectfolders"],
        "summary": "Get all project_folders for my organization",
        "description": "Get all project_folders for my organization",
        "operationId": "get_all_project_folders_for_my_organization_organization_me_project_folders_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organization/{organization_id}/project-folders": {
      "get": {
        "tags": ["Projectfolders"],
        "summary": "Get all project_folders for an organization",
        "description": "Get all project_folders for an organization",
        "operationId": "get_all_project_folders_for_project_organization__organization_id__project_folders_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cross-sections/": {
      "get": {
        "tags": ["CrossSections"],
        "summary": "Get all cross_sections - Sodex only",
        "description": "Get all cross_sections",
        "operationId": "get_all_cross_sections_cross_sections__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/cross-sections/{cross_section_project_id}": {
      "get": {
        "tags": ["CrossSections"],
        "summary": "Get cross_section by id",
        "description": "Get cross_section by id",
        "operationId": "get_cross_section_by_id_cross_sections__cross_section_project_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["CrossSections"],
        "summary": "Update cross_section",
        "description": "Update cross_section",
        "operationId": "update_cross_section_cross_sections__cross_section_project_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["CrossSections"],
        "summary": "Delete cross_section",
        "description": "Delete cross_section",
        "operationId": "delete_cross_section_cross_sections__cross_section_project_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/cross-sections": {
      "get": {
        "tags": ["CrossSections"],
        "summary": "Get all cross_sections for a project",
        "description": "Get all cross_sections for a project",
        "operationId": "get_all_cross_sections_for_project_projects__project_id__cross_sections_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["CrossSections"],
        "summary": "Create new cross_section for a project",
        "description": "Create new cross_section for a project",
        "operationId": "create_cross_section_for_project_projects__project_id__cross_sections_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/tobe-terrains/": {
      "get": {
        "tags": ["Tobeterrains"],
        "summary": "Get all tobe_terrains - Sodex only",
        "description": "Get all tobe_terrains",
        "operationId": "get_all_tobe_terrains_tobe_terrains__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/tobe-terrains/{tobe_terrain_id}": {
      "get": {
        "tags": ["Tobeterrains"],
        "summary": "Get tobe_terrain by id",
        "description": "Get tobe_terrain by id",
        "operationId": "get_tobe_terrain_by_id_tobe_terrains__tobe_terrain_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Tobeterrains"],
        "summary": "Update tobe_terrain",
        "description": "Update tobe_terrain",
        "operationId": "update_tobe_terrain_tobe_terrains__tobe_terrain_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Tobeterrains"],
        "summary": "Delete tobe_terrain",
        "description": "Delete tobe_terrain",
        "operationId": "delete_tobe_terrain_tobe_terrains__tobe_terrain_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/tobe-terrains": {
      "get": {
        "tags": ["Tobeterrains"],
        "summary": "Get all tobe_terrains of a project",
        "description": "Get all tobe_terrains of a project",
        "operationId": "get_project_tobe_terrains_projects__project_id__tobe_terrains_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/{file_id}/tobe-terrains": {
      "post": {
        "tags": ["Tobeterrains"],
        "summary": "Create new tobe_terrain for snapshot",
        "description": "Create new tobe_terrain for snapshot. If no name is set, the file name will be used.",
        "operationId": "create_snapshot_tobe_terrain_files__file_id__tobe_terrains_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/piles-geofences/": {
      "get": {
        "tags": ["Pilegeofences"],
        "summary": "Get all pile_geofences - Sodex only",
        "description": "Get all pile_geofences",
        "operationId": "get_all_pile_geofences_piles_geofences__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/piles-geofences/{pile_geofence_id}": {
      "get": {
        "tags": ["Pilegeofences"],
        "summary": "Get pile_geofence by id",
        "description": "Get pile_geofence by id",
        "operationId": "get_pile_geofence_by_id_piles_geofences__pile_geofence_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Pilegeofences"],
        "summary": "Update pile_geofence",
        "description": "Update pile_geofence",
        "operationId": "update_pile_geofence_piles_geofences__pile_geofence_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Pilegeofences"],
        "summary": "Delete pile_geofence",
        "description": "Delete pile_geofence",
        "operationId": "delete_pile_geofence_piles_geofences__pile_geofence_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/piles/{pile_id}/geofences": {
      "get": {
        "tags": ["Pilegeofences"],
        "summary": "Get all pile_geofences of a pile",
        "description": "Get all pile_geofences of a pile",
        "operationId": "get_all_pile_geofences_of_pile_piles__pile_id__geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/piles/{pile_id}/snapshots/{snapshot_id}/geofences": {
      "get": {
        "tags": ["Pilegeofences"],
        "summary": "Get pile_geofence of a pile at a snapshot",
        "description": "Get pile_geofence of a pile at a snapshot",
        "operationId": "get_pile_geofence_of_pile_at_snapshot_piles__pile_id__snapshots__snapshot_id__geofences_get"
      }
    },
    "/piles/{pile_id}/snapshot/{snapshot_id}/geofences": {
      "post": {
        "tags": ["Pilegeofences"],
        "summary": "Create new pile_geofence",
        "description": "Create new pile_geofence",
        "operationId": "create_pile_geofence_piles__pile_id__snapshot__snapshot_id__geofences_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/visconfigs/": {
      "get": {
        "tags": ["Visconfigs"],
        "summary": "Get all visconfigs - Sodex only",
        "description": "Get all visconfigs",
        "operationId": "get_all_visconfigs_visconfigs__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/visconfigs/{visconfig_id}": {
      "get": {
        "tags": ["Visconfigs"],
        "summary": "Get visconfig by id",
        "description": "Get visconfig by id",
        "operationId": "get_visconfig_by_id_visconfigs__visconfig_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Visconfigs"],
        "summary": "Update visconfig",
        "description": "Update visconfig",
        "operationId": "update_visconfig_visconfigs__visconfig_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Visconfigs"],
        "summary": "Delete visconfig",
        "description": "Delete visconfig",
        "operationId": "delete_visconfig_visconfigs__visconfig_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/visconfigs/me": {
      "get": {
        "tags": ["Visconfigs"],
        "summary": "Get user visconfigs for this project",
        "description": "Get user visconfigs for this project",
        "operationId": "get_user_visconfigs_for_project_projects__project_id__visconfigs_me_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["user"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/visconfigs": {
      "post": {
        "tags": ["Visconfigs"],
        "summary": "Create new visconfig",
        "description": "Create new visconfig",
        "operationId": "create_visconfig_projects__project_id__visconfigs_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/scanblockareas/": {
      "get": {
        "tags": ["Scanblockareas"],
        "summary": "Get all scanblockareas - Sodex only",
        "description": "Get all scanblockareas",
        "operationId": "get_all_scanblockareas_scanblockareas__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/scanblockareas/{scanblockarea_id}": {
      "get": {
        "tags": ["Scanblockareas"],
        "summary": "Get scanblockarea by id",
        "description": "Get scanblockarea by id",
        "operationId": "get_scanblockarea_by_id_scanblockareas__scanblockarea_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Scanblockareas"],
        "summary": "Update scanblockarea",
        "description": "Update scanblockarea",
        "operationId": "update_scanblockarea_scanblockareas__scanblockarea_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Scanblockareas"],
        "summary": "Delete scanblockarea",
        "description": "Delete scanblockarea",
        "operationId": "delete_scanblockarea_scanblockareas__scanblockarea_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/scanblockareas": {
      "get": {
        "tags": ["Scanblockareas"],
        "summary": "Get scanblockareas by project id",
        "description": "Get scanblockareas by project id",
        "operationId": "get_scanblockareas_by_project_id_projects__project_id__scanblockareas_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/infomapfilters/": {
      "get": {
        "tags": ["Infomapfilters"],
        "summary": "Get all infomapfilters",
        "description": "Get all infomapfilters",
        "operationId": "get_all_infomapfilters_infomapfilters__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/infomapfilters/me": {
      "get": {
        "tags": ["Infomapfilters"],
        "summary": "Get my infomapfilter for this project",
        "description": "Get my infomapfilter for this project. If non exist, a default filter is created and returned.",
        "operationId": "get_all_infomapfilters_by_project_projects__project_id__infomapfilters_me_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Infomapfilters"],
        "summary": "Create my infomapfilter for this project",
        "description": "Create my infomapfilter for this project",
        "operationId": "create_infomapfilter_by_project_projects__project_id__infomapfilters_me_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/infomapfilters/{infomapfilter_id}": {
      "get": {
        "tags": ["Infomapfilters"],
        "summary": "Get infomapfilter by id",
        "description": "Get infomapfilter by id",
        "operationId": "get_infomapfilter_by_id_infomapfilters__infomapfilter_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Infomapfilters"],
        "summary": "Update infomapfilter",
        "description": "Update infomapfilter",
        "operationId": "update_infomapfilter_infomapfilters__infomapfilter_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Infomapfilters"],
        "summary": "Delete infomapfilter",
        "description": "Delete infomapfilter",
        "operationId": "delete_infomapfilter_infomapfilters__infomapfilter_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/infomapfilters/geofences": {
      "patch": {
        "tags": ["Infomapfilters"],
        "summary": "Update infomapfilters",
        "description": "Update infomapfilters",
        "operationId": "update_infomapfilters_by_project_projects__project_id__infomapfilters_geofences_patch",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/layers/": {
      "get": {
        "tags": ["Layers"],
        "summary": "Get all layers - Sodex only",
        "description": "Get all layers (access only to Sodex users)",
        "operationId": "get_all_layers_layers__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/layers/{layer_id}": {
      "get": {
        "tags": ["Layers"],
        "summary": "Get layer by id",
        "description": "Get layer by id",
        "operationId": "get_layer_by_id_layers__layer_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Layers"],
        "summary": "Update layer",
        "description": "Update layer",
        "operationId": "update_layer_layers__layer_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Layers"],
        "summary": "Delete layer",
        "description": "Delete layer",
        "operationId": "delete_layer_layers__layer_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/layers": {
      "get": {
        "tags": ["Layers"],
        "summary": "Get layers by project id",
        "description": "Get layers by project id",
        "operationId": "get_layers_by_project_id_projects__project_id__layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Layers"],
        "summary": "Create new layer for this project",
        "description": "Create new layer for this project",
        "operationId": "create_layer_projects__project_id__layers_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/systems/me/layers": {
      "get": {
        "tags": ["Layers"],
        "summary": "Get this systems layers by project id",
        "description": "Get this systems layers by project id",
        "operationId": "get_layers_by_project_id_this_system_projects__project_id__systems_me_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Layers"],
        "summary": "Create new layer for this project for this system",
        "description": "Create new layer for this project for this system",
        "operationId": "create_layer_this_system_projects__project_id__systems_me_layers_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/layers/{layer_id}/process": {
      "post": {
        "tags": ["Layers"],
        "summary": "Process layer",
        "description": "Process layer",
        "operationId": "process_layer_layers__layer_id__process_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/layers/{layer_id}/automatic-processing": {
      "post": {
        "tags": ["Layers"],
        "summary": "Process layer automatically",
        "description": "Process layer automatically",
        "operationId": "automatic_processing_layer_layers__layer_id__automatic_processing_post",
        "security": [
          {
            "APIKeyHeader": []
          }
        ]
      }
    },
    "/systems/{system_id}/layers/datavolume-3d": {
      "get": {
        "tags": ["Layers"],
        "summary": "Get System Layer 3D data volume",
        "description": "Get System Layer 3D data volume in GB",
        "operationId": "get_system_3d_data_volume_systems__system_id__layers_datavolume_3d_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/layers/datavolume-3d": {
      "get": {
        "tags": ["Layers"],
        "summary": "Get Project Layer 3D data volume",
        "description": "Get Project Layer 3D data volume in GB",
        "operationId": "get_project_3d_data_volume_projects__project_id__layers_datavolume_3d_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/coordinatesystems/": {
      "get": {
        "tags": ["Coordinatesystems"],
        "summary": "Get all coordinatesystems - Sodex only",
        "description": "Get all coordinatesystems",
        "operationId": "get_all_coordinatesystems_coordinatesystems__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      },
      "post": {
        "tags": ["Coordinatesystems"],
        "summary": "Create new coordinatesystem",
        "description": "Create new coordinatesystem",
        "operationId": "create_coordinatesystem_coordinatesystems__post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/coordinatesystems/{coordinatesystem_id}": {
      "get": {
        "tags": ["Coordinatesystems"],
        "summary": "Get coordinatesystem by id",
        "description": "Get coordinatesystem by id",
        "operationId": "get_coordinatesystem_by_id_coordinatesystems__coordinatesystem_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Coordinatesystems"],
        "summary": "Update coordinatesystem",
        "description": "Update coordinatesystem",
        "operationId": "update_coordinatesystem_coordinatesystems__coordinatesystem_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Coordinatesystems"],
        "summary": "Delete coordinatesystem",
        "description": "Delete coordinatesystem",
        "operationId": "delete_coordinatesystem_coordinatesystems__coordinatesystem_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/coordinatesystems": {
      "get": {
        "tags": ["Coordinatesystems"],
        "summary": "Get coordinatesystems by project id",
        "description": "Get coordinatesystems by project id",
        "operationId": "get_coordinatesystems_by_project_id_projects__project_id__coordinatesystems_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/coordinatesystems/{coordinatesystem_id}/calibration-file": {
      "get": {
        "tags": ["Coordinatesystems"],
        "summary": "Get Coordinatesystem Calibration File",
        "description": "Get coord-system calibration file",
        "operationId": "get_coordinatesystem_calibration_file_coordinatesystems__coordinatesystem_id__calibration_file_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/coordinatesystems/calibration-file": {
      "get": {
        "tags": ["Coordinatesystems"],
        "summary": "Get Project Coordinatesystem Calibration File",
        "description": "Get project coord-system calibration file",
        "operationId": "get_project_coordinatesystem_calibration_file_projects__project_id__coordinatesystems_calibration_file_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/coordinatesystems/lok-file-validation": {
      "post": {
        "tags": ["Coordinatesystems"],
        "summary": "Validate lok file",
        "description": "Validate lok file",
        "operationId": "validate_lok_file_coordinatesystems_lok_file_validation_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/correctionservices/": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get all correctionservices - Sodex only",
        "description": "Get all correctionservices",
        "operationId": "get_all_correctionservices_correctionservices__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/correctionservices/{correction_service_id}": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get correctionservice by id",
        "description": "Get correctionservice by id",
        "operationId": "get_correctionservice_by_id_correctionservices__correction_service_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Correctionservices"],
        "summary": "Update correctionservice",
        "description": "Update correctionservice",
        "operationId": "update_correctionservice_correctionservices__correction_service_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Correctionservices"],
        "summary": "Delete correctionservice",
        "description": "Delete correctionservice",
        "operationId": "delete_correctionservice_correctionservices__correction_service_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/projects/{project_id}/correctionservices": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get my correctionservices by project id",
        "description": "Get correctionservices by project id",
        "operationId": "get_correctionservices_by_project_id_me_systems_me_projects__project_id__correctionservices_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Correctionservices"],
        "summary": "Create new correctionservice for me",
        "description": "Create new correctionservice for me",
        "operationId": "create_correctionservice_me_systems_me_projects__project_id__correctionservices_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/correctionservices": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get my correctionservices",
        "description": "Get my correctionservices",
        "operationId": "get_correctionservices_by_system_id_me_systems_me_correctionservices_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/projects/{project_id}/correctionservices": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get system correctionservices by project id",
        "description": "Get correctionservices by project id",
        "operationId": "get_correctionservices_by_project_id_systems__system_id__projects__project_id__correctionservices_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Correctionservices"],
        "summary": "Create new correctionservice for system for project",
        "description": "Create new correctionservice for system for project",
        "operationId": "create_project_system_correctionservice_systems__system_id__projects__project_id__correctionservices_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/correctionservices": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get correctionservices by system id",
        "description": "Get correctionservices by system id",
        "operationId": "get_correctionservices_by_system_id_systems__system_id__correctionservices_get"
      },
      "post": {
        "tags": ["Correctionservices"],
        "summary": "Create new correctionservice",
        "description": "Create new correctionservice",
        "operationId": "create_correctionservice_systems__system_id__correctionservices_post"
      }
    },
    "/correctionservices/validate": {
      "post": {
        "tags": ["Correctionservices"],
        "summary": "Validate project correctionservice",
        "description": "Validate project correctionservice",
        "operationId": "validate_correctionservice_correctionservices_validate_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/correctionservices-ntrip-mountpoints": {
      "get": {
        "tags": ["Correctionservices"],
        "summary": "Get ntrip mountpoints",
        "description": "Get ntrip mountpoints",
        "operationId": "get_ntrip_mountpoints_correctionservices_ntrip_mountpoints_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/dashboards/": {
      "get": {
        "tags": ["Dashboards"],
        "summary": "Get all dashboards - Sodex only",
        "description": "Get all dashboards",
        "operationId": "get_all_dashboards_dashboards__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/dashboards/export": {
      "post": {
        "tags": ["Dashboards"],
        "summary": "Export dashboard",
        "description": "Export dashboard",
        "operationId": "export_dashboard_dashboards_export_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/dashboards/{dashboard_id}/share": {
      "get": {
        "tags": ["Dashboards"],
        "summary": "Create a share token for this dashboard",
        "description": "Create a share token for this dashboard",
        "operationId": "create_share_token_dashboards__dashboard_id__share_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/dashboards/{dashboard_id}": {
      "get": {
        "tags": ["Dashboards"],
        "summary": "Get dashboard by id",
        "description": "Get dashboard by id",
        "operationId": "get_dashboard_by_id_dashboards__dashboard_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Dashboards"],
        "summary": "Update dashboard",
        "description": "Update dashboard",
        "operationId": "update_dashboard_dashboards__dashboard_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Dashboards"],
        "summary": "Delete dashboard",
        "description": "Delete dashboard",
        "operationId": "delete_dashboard_dashboards__dashboard_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/dashboards": {
      "get": {
        "tags": ["Dashboards"],
        "summary": "Get dashboards by project id",
        "description": "Get dashboards by project id",
        "operationId": "get_dashboards_by_project_id_projects__project_id__dashboards_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Dashboards"],
        "summary": "Create new dashboard for this project",
        "description": "Create new dashboard for this project",
        "operationId": "create_dashboard_projects__project_id__dashboards_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/dashboards/{dashboard_id}/export": {
      "post": {
        "tags": ["Dashboards"],
        "summary": "Export dashboard by id",
        "description": "Export dashboard by id",
        "operationId": "export_dashboard_by_id_dashboards__dashboard_id__export_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/": {
      "get": {
        "tags": ["Files"],
        "summary": "Get all files",
        "description": "Get all files",
        "operationId": "get_all_files_files__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      },
      "post": {
        "tags": ["Files"],
        "summary": "Create new file",
        "description": "Create new file",
        "operationId": "create_file_files__post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "user"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files": {
      "get": {
        "tags": ["Files"],
        "summary": "Get all files of a project",
        "description": "Get all files of a project",
        "operationId": "get_all_files_of_project_projects__project_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/me/files/size": {
      "get": {
        "tags": ["Files"],
        "summary": "Get total size of all files of the organization",
        "description": "Get total size of all files of the organization",
        "operationId": "get_total_size_of_organization_files_organizations_me_files_size_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/files/size": {
      "get": {
        "tags": ["Files"],
        "summary": "Get files size by organization",
        "description": "Get files size by organization",
        "operationId": "get_gb_size_of_organization_files_organizations__organization_id__files_size_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files/size": {
      "get": {
        "tags": ["Files"],
        "summary": "Get total size of all files of the user",
        "description": "Get total size of all files of the user",
        "operationId": "get_total_size_of_user_files_projects__project_id__files_size_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["user"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/{file_id}": {
      "get": {
        "tags": ["Files"],
        "summary": "Get file by id",
        "description": "Get file by id",
        "operationId": "get_file_by_id_files__file_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Files"],
        "summary": "Update file",
        "description": "Update file",
        "operationId": "update_file_files__file_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Files"],
        "summary": "Delete file",
        "description": "Delete file",
        "operationId": "delete_file_files__file_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/{file_id}/url": {
      "get": {
        "tags": ["Files"],
        "summary": "Get signed file url by id",
        "description": "Get signed file url by id",
        "operationId": "get_file_url_by_id_files__file_id__url_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files/part-put-url": {
      "get": {
        "tags": ["Files"],
        "summary": "Get File Part Put Url",
        "operationId": "get_file_part_put_url_projects__project_id__files_part_put_url_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files/multipart-upload": {
      "get": {
        "tags": ["Files"],
        "summary": "Get File Multipart Upload",
        "operationId": "get_file_multipart_upload_projects__project_id__files_multipart_upload_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files/put-url": {
      "get": {
        "tags": ["Files"],
        "summary": "Get File Put Url",
        "operationId": "get_file_put_url_projects__project_id__files_put_url_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/assets": {
      "post": {
        "tags": ["Files"],
        "summary": "Create new file in the assets bucket",
        "description": "Create new file in the assets bucket",
        "operationId": "create_assets_file_files_assets_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "user"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/put-url": {
      "post": {
        "tags": ["Files"],
        "summary": "Create New File By Put Url",
        "description": "Create New File By Put Url",
        "operationId": "create_file_by_put_url_files_put_url_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files/{filetype}": {
      "get": {
        "tags": ["Files"],
        "summary": "Get all files of a project by type",
        "description": "Get all files of a project by type",
        "operationId": "get_all_files_of_project_by_type_projects__project_id__files__filetype__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/{file_id}/linked-to-snapshot": {
      "get": {
        "tags": ["Files"],
        "summary": "Is file linked snapshot",
        "description": "Is file linked to snapshot",
        "operationId": "is_file_linked_to_snapshot_files__file_id__linked_to_snapshot_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/files/upload/stream": {
      "post": {
        "tags": ["Files"],
        "summary": "Upload File Stream",
        "operationId": "upload_file_stream_projects__project_id__files_upload_stream_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/files/calculate-pixel-count": {
      "post": {
        "tags": ["Files"],
        "summary": "Calculate Images Pixel Count",
        "description": "Calculate Images Pixel Count",
        "operationId": "calculate_images_pixel_count_files_calculate_pixel_count_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          }
        ]
      }
    },
    "/files/calculate-credits-cost": {
      "post": {
        "tags": ["Files"],
        "summary": "Calculate Images Credits Cost",
        "description": "Calculate Images Credits Cost",
        "operationId": "calculate_images_credits_cost_files_calculate_credits_cost_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          }
        ]
      }
    },
    "/folders/{folder_id}/files": {
      "get": {
        "tags": ["Files"],
        "summary": "Get all files of a folder",
        "description": "Get all files of a folder",
        "operationId": "get_all_files_of_folder_folders__folder_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/folders/": {
      "get": {
        "tags": ["Folders"],
        "summary": "Get all folders",
        "description": "Get all folders",
        "operationId": "get_all_folders_folders__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "post": {
        "tags": ["Folders"],
        "summary": "Create new folder",
        "description": "Create new folder",
        "operationId": "create_folder_folders__post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/explorer": {
      "get": {
        "tags": ["Folders"],
        "summary": "Get project explorer",
        "description": "Get project explorer",
        "operationId": "get_project_explorer_projects__project_id__explorer_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/folders/{folder_id}": {
      "get": {
        "tags": ["Folders"],
        "summary": "Get folder by id",
        "description": "Get folder by id",
        "operationId": "get_folder_by_id_folders__folder_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "vidoc"]
          }
        ]
      },
      "put": {
        "tags": ["Folders"],
        "summary": "Update folder",
        "description": "Update folder",
        "operationId": "update_folder_folders__folder_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      },
      "delete": {
        "tags": ["Folders"],
        "summary": "Delete folder",
        "description": "Delete folder",
        "operationId": "delete_folder_folders__folder_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/folders/{folder_id}/copy": {
      "patch": {
        "tags": ["Folders"],
        "summary": "Copy files and folders into this folder",
        "description": "Copy files and folders into this folder",
        "operationId": "copy_files_into_folder_folders__folder_id__copy_patch",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/folders/{folder_id}/move": {
      "patch": {
        "tags": ["Folders"],
        "summary": "Move files into this folder",
        "description": "Move files into this folder",
        "operationId": "move_files_into_folder_folders__folder_id__move_patch",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/projects/{project_id}/explorer/zip-download": {
      "post": {
        "tags": ["Folders"],
        "summary": "Zip Folder Download",
        "description": "Download a folder and files as a zip file",
        "operationId": "project_explorer_zip_download_projects__project_id__explorer_zip_download_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/folders/{folder_id}/pixel-count": {
      "get": {
        "tags": ["Folders"],
        "summary": "Get Folder Images Pixel Count",
        "description": "Get pixel count of all images in a folder",
        "operationId": "get_folder_images_pixel_count_folders__folder_id__pixel_count_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/folders/{folder_id}/datavolume": {
      "get": {
        "tags": ["Folders"],
        "summary": "Get Folder Datavolume",
        "description": "Get datavolume of all files in a folder only on level 1. Subfolders are not included. Size in GB",
        "operationId": "get_folder_images_datavolume_folders__folder_id__datavolume_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/folders/{folder_id}/sub-folders": {
      "get": {
        "tags": ["Folders"],
        "summary": "Get all subfolders of a folder",
        "description": "Get all subfolders of a folder",
        "operationId": "get_folder_sub_folders_folders__folder_id__sub_folders_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/geofences/": {
      "get": {
        "tags": ["Geofences"],
        "summary": "Get all geofences - Sodex only",
        "description": "Get all geofences",
        "operationId": "get_all_geofences_geofences__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/geofences/{geofence_id}": {
      "get": {
        "tags": ["Geofences"],
        "summary": "Get geofence by id",
        "description": "Get geofence by id",
        "operationId": "get_geofence_by_id_geofences__geofence_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Geofences"],
        "summary": "Update geofence",
        "description": "Update geofence",
        "operationId": "update_geofence_geofences__geofence_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Geofences"],
        "summary": "Delete geofence",
        "description": "Delete geofence",
        "operationId": "delete_geofence_geofences__geofence_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/geofences": {
      "get": {
        "tags": ["Geofences"],
        "summary": "Get geofences by project id",
        "description": "Get geofences by project id",
        "operationId": "get_geofences_by_project_id_projects__project_id__geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Geofences"],
        "summary": "Create new geofence for this project",
        "description": "Create new geofence for this project",
        "operationId": "create_geofence_projects__project_id__geofences_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/orthophotos/": {
      "get": {
        "tags": ["Orthophotos"],
        "summary": "Get all Orthophotos - Sodex only",
        "description": "Get all Orthophotos",
        "operationId": "get_all_orthophotos_orthophotos__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/orthophotos": {
      "get": {
        "tags": ["Orthophotos"],
        "summary": "Get Project Orthophotos",
        "description": "Get Project Orthophotos",
        "operationId": "get_project_orthophotos_projects__project_id__orthophotos_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Orthophotos"],
        "summary": "Create Project Orthophoto",
        "description": "Create Project Orthophoto",
        "operationId": "create_project_orthophoto_projects__project_id__orthophotos_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/orthophotos/{orthophoto_id}": {
      "get": {
        "tags": ["Orthophotos"],
        "summary": "Get Orthophoto by id",
        "description": "Get Orthophoto by id",
        "operationId": "get_orthophoto_by_id_orthophotos__orthophoto_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Orthophotos"],
        "summary": "Update Orthophoto",
        "description": "Update Orthophoto",
        "operationId": "update_orthophoto_orthophotos__orthophoto_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Orthophotos"],
        "summary": "Delete Orthophoto",
        "description": "Delete Orthophoto",
        "operationId": "delete_orthophoto_orthophotos__orthophoto_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/project-tags/{project_tag_id}/orthophotos": {
      "get": {
        "tags": ["Orthophotos"],
        "summary": "Get orthophotos by project tag",
        "description": "Get orthophotos by project tag",
        "operationId": "get_orthophotos_by_project_tag_project_tags__project_tag_id__orthophotos_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshots/{snapshot_id}/orthophoto": {
      "get": {
        "tags": ["Orthophotos"],
        "summary": "Get snapshot orthophoto",
        "description": "Get snapshot orthophoto",
        "operationId": "get_snapshot_orthophoto_snapshots__snapshot_id__orthophoto_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/phases/": {
      "get": {
        "tags": ["Phases"],
        "summary": "Get all phases",
        "description": "Get all phases",
        "operationId": "get_all_phases_phases__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest", "sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/phases": {
      "get": {
        "tags": ["Phases"],
        "summary": "Get all phases by project",
        "description": "Get all phases by project",
        "operationId": "get_all_phases_by_project_projects__project_id__phases_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Phases"],
        "summary": "Create new phase",
        "description": "Create new phase",
        "operationId": "create_phase_projects__project_id__phases_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/phases/{phase_id}": {
      "get": {
        "tags": ["Phases"],
        "summary": "Get phase by id",
        "description": "Get phase by id",
        "operationId": "get_phase_by_id_phases__phase_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Phases"],
        "summary": "Update phase",
        "description": "Update phase",
        "operationId": "update_phase_phases__phase_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Phases"],
        "summary": "Delete phase",
        "description": "Delete phase",
        "operationId": "delete_phase_phases__phase_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/phases/{phase_id}/state": {
      "put": {
        "tags": ["Phases"],
        "summary": "Update phase state",
        "description": "Update phase state",
        "operationId": "update_phase_state_phases__phase_id__state_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["system", "cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/phases/{phase_id}/order": {
      "put": {
        "tags": ["Phases"],
        "summary": "Update phase order",
        "description": "Update phase order",
        "operationId": "update_phase_order_phases__phase_id__order_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/piles/": {
      "get": {
        "tags": ["Piles"],
        "summary": "Get all piles - Sodex Only",
        "description": "Get all piles - Sodex Only",
        "operationId": "get_all_piles_piles__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/storages/{storage_id}/piles": {
      "get": {
        "tags": ["Piles"],
        "summary": "Get all piles",
        "description": "Get all piles",
        "operationId": "get_all_piles_by_storage_storages__storage_id__piles_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Piles"],
        "summary": "Create new pile",
        "description": "Create new pile",
        "operationId": "create_pile_storages__storage_id__piles_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/piles/{pile_id}": {
      "get": {
        "tags": ["Piles"],
        "summary": "Get pile by id",
        "description": "Get pile by id",
        "operationId": "get_pile_by_id_piles__pile_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Piles"],
        "summary": "Update pile",
        "description": "Update pile",
        "operationId": "update_pile_piles__pile_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Piles"],
        "summary": "Delete pile",
        "description": "Delete pile",
        "operationId": "delete_pile_piles__pile_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get all projects",
        "description": "Get all projects",
        "operationId": "get_all_projects_projects__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/assets/auth": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get auth url for project assets",
        "description": "Get auth url for project assets",
        "operationId": "get_project_assets_auth_url_projects__project_id__assets_auth_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/potrees/auth": {
      "get": {
        "tags": ["Projects", "Potree"],
        "summary": "Get auth url for project potree",
        "description": "Get auth url for project potree",
        "operationId": "get_project_potree_auth_url_projects__project_id__potrees_auth_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/admins": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get admins by project id",
        "description": "Get admins by project id",
        "operationId": "get_admins_by_project_id_projects__project_id__admins_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Projects"],
        "summary": "Add admins to project",
        "description": "Add user as admins to project",
        "operationId": "add_admins_to_project_projects__project_id__admins_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Projects"],
        "summary": "Remove admins from project",
        "description": "Remove admins from project.",
        "operationId": "remove_admins_from_project_projects__project_id__admins_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/members": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get members by project id",
        "description": "Get members by project id",
        "operationId": "get_members_by_project_id_projects__project_id__members_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Projects"],
        "summary": "Add members to project",
        "description": "Add user as members to project",
        "operationId": "add_users_to_project_projects__project_id__members_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Projects"],
        "summary": "Remove users from project",
        "description": "Remove users from project",
        "operationId": "remove_members_from_project_projects__project_id__members_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/systems": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get systems by project id",
        "description": "Get systems by project id",
        "operationId": "get_systems_by_project_id_projects__project_id__systems_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Projects"],
        "summary": "Add systems to project",
        "description": "Add systems to project",
        "operationId": "add_systems_to_project_projects__project_id__systems_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Projects"],
        "summary": "Remove systems from project",
        "description": "Remove systems from project",
        "operationId": "remove_systems_from_project_projects__project_id__systems_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/me/projects/no-access": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get all projects in my organization that I don't have access to",
        "description": "Get all projects in my organization that I don't have access to",
        "operationId": "get_my_organizations_no_access_projects_organizations_me_projects_no_access_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/me/projects": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get all projects in my organization",
        "description": "Get all projects in my organization",
        "operationId": "get_my_organizations_projects_organizations_me_projects_get",
        "security": [
          {
            "OAuth2PasswordBearer": [
              "cloud_base",
              "guest",
              "system",
              "vidoc",
              "inactive"
            ]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Projects"],
        "summary": "Create new project in my organization",
        "description": "Create new project in my organization",
        "operationId": "create_project_in_my_organization_organizations_me_projects_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/projects": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get all projects in organization",
        "description": "Get all projects in organization",
        "operationId": "get_organizations_projects_organizations__organization_id__projects_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Projects"],
        "summary": "Create new project",
        "description": "Create new project",
        "operationId": "create_project_organizations__organization_id__projects_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get project by id",
        "description": "Get project by id",
        "operationId": "get_project_by_id_projects__project_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Projects"],
        "summary": "Update project",
        "description": "Update project",
        "operationId": "update_project_projects__project_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Projects"],
        "summary": "Delete project",
        "description": "Delete project",
        "operationId": "delete_project_projects__project_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/volume/cut-and-fill": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get project volume cut and fill",
        "description": "Get project volume cut and fill in m3",
        "operationId": "get_project_volume_cut_and_fill_projects__project_id__volume_cut_and_fill_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/project-folders/{project_folder_id}/projects": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get projects by project_folder id",
        "description": "Get projects by project_folder id",
        "operationId": "get_projects_by_project_folder_id_project_folders__project_folder_id__projects_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/projects": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get this system projects",
        "description": "Get this system projects",
        "operationId": "get_system_projects_systems_me_projects_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/projects": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get projects by system id",
        "description": "Get projects by system id",
        "operationId": "get_projects_by_system_id_systems__system_id__projects_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          }
        ]
      }
    },
    "/projects/{project_id}/3d-timelapse": {
      "post": {
        "tags": ["Projects"],
        "summary": "Create 3D timelapse",
        "description": "Create 3D timelapse",
        "operationId": "create_project_3d_timelapse_projects__project_id__3d_timelapse_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/process-migration": {
      "post": {
        "tags": ["Projects"],
        "summary": "Process Project Migration",
        "operationId": "process_project_migration_projects__project_id__process_migration_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/viscan-scin-upload": {
      "get": {
        "tags": ["Projects"],
        "summary": "Get Viscan Scin Upload Credentials",
        "operationId": "get_viscan_scin_upload_credentials_projects__project_id__viscan_scin_upload_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc", "inactive"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/telekom-sma-valid": {
      "get": {
        "tags": ["Projects"],
        "summary": "Is Telekom Sma Valid",
        "operationId": "is_telekom_sma_valid_projects__project_id__telekom_sma_valid_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "vidoc", "inactive"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/scantasks/": {
      "get": {
        "tags": ["Scantasks"],
        "summary": "Get all scantasks - Sodex only",
        "description": "Get all scantasks",
        "operationId": "get_all_scantasks_scantasks__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/scantasks": {
      "get": {
        "tags": ["Scantasks"],
        "summary": "Get scantasks by project id",
        "description": "Get scantasks by project id",
        "operationId": "get_scantasks_by_project_id_projects__project_id__scantasks_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Scantasks"],
        "summary": "Create new scantask for this project",
        "description": "Create new scantask for this project",
        "operationId": "create_scantask_projects__project_id__scantasks_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/scantasks/{scantask_id}": {
      "get": {
        "tags": ["Scantasks"],
        "summary": "Get scantask by id",
        "description": "Get scantask by id",
        "operationId": "get_scantask_by_id_scantasks__scantask_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Scantasks"],
        "summary": "Update scantask",
        "description": "Update scantask",
        "operationId": "update_scantask_scantasks__scantask_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Scantasks"],
        "summary": "Delete scantask",
        "description": "Delete scantask",
        "operationId": "delete_scantask_scantasks__scantask_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/scantasks/{scantask_id}/images": {
      "get": {
        "tags": ["Scantasks"],
        "summary": "Get images from scantask",
        "description": "Get signed s3 url from images from scantask",
        "operationId": "get_images_from_scantask_scantasks__scantask_id__images_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Scantasks"],
        "summary": "Add images to scantask",
        "description": "Add images to scantask",
        "operationId": "add_images_to_scantask_scantasks__scantask_id__images_post",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/soils/": {
      "get": {
        "tags": ["Soils"],
        "summary": "Get all soils - Sodex only",
        "description": "Get all soils",
        "operationId": "get_all_soils_soils__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/soils/{soil_id}": {
      "get": {
        "tags": ["Soils"],
        "summary": "Get soil by id",
        "description": "Get soil by id",
        "operationId": "get_soil_by_id_soils__soil_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Soils"],
        "summary": "Update soil",
        "description": "Update soil",
        "operationId": "update_soil_soils__soil_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Soils"],
        "summary": "Delete soil",
        "description": "Delete soil",
        "operationId": "delete_soil_soils__soil_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/me/soils": {
      "get": {
        "tags": ["Soils"],
        "summary": "Get soils by organization id",
        "description": "Get soils by organization id",
        "operationId": "get_soils_by_organization_id_organizations_me_soils_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/soils": {
      "get": {
        "tags": ["Soils"],
        "summary": "Get soils by project id",
        "description": "Get soils by project id",
        "operationId": "get_soils_by_project_id_projects__project_id__soils_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Soils"],
        "summary": "Create new soil for this project",
        "description": "Create new soil for this project",
        "operationId": "create_soil_projects__project_id__soils_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/soils/import": {
      "post": {
        "tags": ["Soils"],
        "summary": "Import soils for this project",
        "description": "Import soils for this project",
        "operationId": "import_soils_projects__project_id__soils_import_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/storages/": {
      "get": {
        "tags": ["Storages"],
        "summary": "Get all storages - Sodex Only",
        "description": "Get all storages - Sodex Only",
        "operationId": "get_all_storages_storages__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/storages": {
      "get": {
        "tags": ["Storages"],
        "summary": "Get storages by project id",
        "description": "Get storages by project id",
        "operationId": "get_storages_by_project_id_projects__project_id__storages_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Storages"],
        "summary": "Create new storage",
        "description": "Create new storage",
        "operationId": "create_storage_projects__project_id__storages_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/storages/{storage_id}": {
      "get": {
        "tags": ["Storages"],
        "summary": "Get storage by id",
        "description": "Get storage by id",
        "operationId": "get_storage_by_id_storages__storage_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Storages"],
        "summary": "Update storage",
        "description": "Update storage",
        "operationId": "update_storage_storages__storage_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Storages"],
        "summary": "Delete storage",
        "description": "Delete storage",
        "operationId": "delete_Storage_storages__storage_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/storages/{storage_id}/volume": {
      "get": {
        "tags": ["Storages"],
        "summary": "Get Storage Volume",
        "description": "Get storage volume",
        "operationId": "get_storage_volume_storages__storage_id__volume_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/datasets/": {
      "get": {
        "tags": ["Datasets"],
        "summary": "Get all datasets - Sodex only",
        "description": "Get all datasets",
        "operationId": "get_all_datasets_datasets__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/datasets/{dataset_id}": {
      "get": {
        "tags": ["Datasets"],
        "summary": "Get dataset by id",
        "description": "Get dataset by id",
        "operationId": "get_dataset_by_id_datasets__dataset_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["Datasets"],
        "summary": "Update dataset",
        "description": "Update dataset",
        "operationId": "update_dataset_datasets__dataset_id__put"
      },
      "delete": {
        "tags": ["Datasets"],
        "summary": "Delete dataset",
        "description": "Delete dataset",
        "operationId": "delete_dataset_datasets__dataset_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/datasets": {
      "get": {
        "tags": ["Datasets"],
        "summary": "Get project datasets",
        "description": "Get project datasets",
        "operationId": "get_project_datasets_projects__project_id__datasets_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Datasets"],
        "summary": "Create dataset for a project",
        "description": "Create dataset for a project",
        "operationId": "create_project_dataset_projects__project_id__datasets_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/datasets/{dataset_id}/mock": {
      "post": {
        "tags": ["Datasets"],
        "summary": "Mock timeseries dataset",
        "description": "Mock timeseries dataset",
        "operationId": "mock_dataset_datasets__dataset_id__mock_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/lines/": {
      "get": {
        "tags": ["Lines"],
        "summary": "Get all lines - Sodex only",
        "description": "Get all lines",
        "operationId": "get_all_lines_lines__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/lines/{line_id}": {
      "get": {
        "tags": ["Lines"],
        "summary": "Get line by id",
        "description": "Get line by id",
        "operationId": "get_line_by_id_lines__line_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["Lines"],
        "summary": "Update line",
        "description": "Update line",
        "operationId": "update_line_lines__line_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      },
      "delete": {
        "tags": ["Lines"],
        "summary": "Delete line",
        "description": "Delete line",
        "operationId": "delete_line_lines__line_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/lines": {
      "get": {
        "tags": ["Lines"],
        "summary": "Get project lines",
        "description": "Get projec lines",
        "operationId": "get_project_lines_projects__project_id__lines_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Lines"],
        "summary": "Create project line",
        "description": "Create project line",
        "operationId": "create_project_line_projects__project_id__lines_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/cross-sections-project/{cross_section_project_id}/lines": {
      "get": {
        "tags": ["Lines"],
        "summary": "Get lines by cross section project id",
        "description": "Get lines by cross section project id",
        "operationId": "get_cross_section_project_lines_cross_sections_project__cross_section_project_id__lines_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/stored-lines/": {
      "get": {
        "tags": ["Storedlines"],
        "summary": "Get all stored_lines - Sodex only",
        "description": "Get all stored_lines",
        "operationId": "get_all_stored_lines_stored_lines__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/stored-lines/{stored_lines_id}": {
      "get": {
        "tags": ["Storedlines"],
        "summary": "Get stored_lines by id",
        "description": "Get stored_lines by id",
        "operationId": "get_stored_lines_by_id_stored_lines__stored_lines_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["Storedlines"],
        "summary": "Update stored_lines",
        "description": "Update stored_lines",
        "operationId": "update_stored_lines_stored_lines__stored_lines_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      },
      "delete": {
        "tags": ["Storedlines"],
        "summary": "Delete stored_lines",
        "description": "Delete stored_lines",
        "operationId": "delete_stored_lines_stored_lines__stored_lines_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/projects/{project_id}/stored-lines": {
      "get": {
        "tags": ["Storedlines"],
        "summary": "Get project stored_lines",
        "description": "Get project stored_lines",
        "operationId": "get_project_stored_lines_projects__project_id__stored_lines_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Storedlines"],
        "summary": "Create project stored_lines",
        "description": "Create project stored_lines",
        "operationId": "create_project_stored_lines_projects__project_id__stored_lines_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/stored-lines/{stored_lines_id}/point/{point_id}/file": {
      "post": {
        "tags": ["Storedlines"],
        "summary": "Upload files to storedlines point",
        "description": "Upload files to storedlines point",
        "operationId": "upload_file_to_storedlines_point_stored_lines__stored_lines_id__point__point_id__file_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/stored-lines/{stored_lines_id}/point/{point_id}/files": {
      "get": {
        "tags": ["Storedlines"],
        "summary": "Get files of storedlines point",
        "description": "Get files of storedlines point",
        "operationId": "get_files_of_storedlines_point_stored_lines__stored_lines_id__point__point_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "delete": {
        "tags": ["Storedlines"],
        "summary": "Delete all files from storedlines point",
        "description": "Delete all files from storedlines point",
        "operationId": "delete_files_from_storedlines_point_stored_lines__stored_lines_id__point__point_id__files_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/stored-lines/{stored_lines_id}/point/{point_id}/file/{file_id}": {
      "delete": {
        "tags": ["Storedlines"],
        "summary": "Delete file from storedlines point",
        "description": "Delete file from storedlines point",
        "operationId": "delete_file_from_storedlines_point_stored_lines__stored_lines_id__point__point_id__file__file_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/checkpoints/": {
      "get": {
        "tags": ["Checkpointpoints"],
        "summary": "Get all checkpoints - Sodex only",
        "description": "Get all checkpoints",
        "operationId": "get_all_checkpoints_checkpoints__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/checkpoints/{checkpoint_id}": {
      "get": {
        "tags": ["Checkpointpoints"],
        "summary": "Get checkpoint by id",
        "description": "Get checkpoint by id",
        "operationId": "get_checkpoint_by_id_checkpoints__checkpoint_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["Checkpointpoints"],
        "summary": "Update checkpoint",
        "description": "Update checkpoint",
        "operationId": "update_checkpoint_checkpoints__checkpoint_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      },
      "delete": {
        "tags": ["Checkpointpoints"],
        "summary": "Delete checkpoint",
        "description": "Delete checkpoint",
        "operationId": "delete_checkpoint_checkpoints__checkpoint_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/projects/{project_id}/checkpoints": {
      "get": {
        "tags": ["Checkpointpoints"],
        "summary": "Get project checkpoints",
        "description": "Get project checkpoints",
        "operationId": "get_project_checkpoints_projects__project_id__checkpoints_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Checkpointpoints"],
        "summary": "Create project checkpoint",
        "description": "Create project checkpoint",
        "operationId": "create_project_checkpoint_projects__project_id__checkpoints_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/checkpoints/{checkpoint_id}/file": {
      "post": {
        "tags": ["Checkpointpoints"],
        "summary": "Upload files to checkpoint",
        "description": "Upload files to checkpoint",
        "operationId": "upload_file_to_checkpoints_point_checkpoints__checkpoint_id__file_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/checkpoints/{checkpoint_id}/files": {
      "get": {
        "tags": ["Checkpointpoints"],
        "summary": "Get files of checkpoint",
        "description": "Get files of checkpoint",
        "operationId": "get_files_of_checkpoints_point_checkpoints__checkpoint_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "delete": {
        "tags": ["Checkpointpoints"],
        "summary": "Delete all files from checkpoint",
        "description": "Delete all files from checkpoint",
        "operationId": "delete_files_from_checkpoints_point_checkpoints__checkpoint_id__files_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/checkpoints/{checkpoint_id}/file/{file_id}": {
      "delete": {
        "tags": ["Checkpointpoints"],
        "summary": "Delete file from checkpoint",
        "description": "Delete file from checkpoint",
        "operationId": "delete_file_from_checkpoints_point_checkpoints__checkpoint_id__file__file_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      }
    },
    "/stored-points/": {
      "get": {
        "tags": ["Measurements"],
        "summary": "Get all stored_points - Sodex only",
        "description": "Get all stored_points",
        "operationId": "get_all_stored_points_stored_points__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/stored-points/{stored_points_id}": {
      "get": {
        "tags": ["Measurements"],
        "summary": "Get stored_points by id",
        "description": "Get stored_points by id",
        "operationId": "get_stored_points_by_id_stored_points__stored_points_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Measurements"],
        "summary": "Update stored_points",
        "description": "Update stored_points",
        "operationId": "update_stored_points_stored_points__stored_points_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Measurements"],
        "summary": "Delete stored_points",
        "description": "Delete stored_points",
        "operationId": "delete_stored_points_stored_points__stored_points_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/stored-points": {
      "get": {
        "tags": ["Measurements"],
        "summary": "Get stored_points by project id",
        "description": "Get stored_points by project id",
        "operationId": "get_stored_points_by_project_id_projects__project_id__stored_points_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Measurements"],
        "summary": "Create new stored_points for this project",
        "description": "Create new stored_points for this project",
        "operationId": "create_stored_points_projects__project_id__stored_points_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/stored-points/{stored_points_id}/point/{point_id}/file": {
      "post": {
        "tags": ["Measurements"],
        "summary": "Upload files to storedpoints point",
        "description": "Upload files to storedpoints point",
        "operationId": "upload_file_to_storedpoints_point_stored_points__stored_points_id__point__point_id__file_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/stored-points/{stored_points_id}/point/{point_id}/files": {
      "get": {
        "tags": ["Measurements"],
        "summary": "Get files of storedpoints point",
        "description": "Get files of storedpoints point",
        "operationId": "get_files_of_storedpoints_point_stored_points__stored_points_id__point__point_id__files_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Measurements"],
        "summary": "Delete all files from storedpoints point",
        "description": "Delete all files from storedpoints point",
        "operationId": "delete_files_from_storedpoints_point_stored_points__stored_points_id__point__point_id__files_delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/stored-points/{stored_points_id}/point/{point_id}/file/{file_id}": {
      "delete": {
        "tags": ["Measurements"],
        "summary": "Delete file from storedpoints point",
        "description": "Delete file from storedpoints point",
        "operationId": "delete_file_from_storedpoints_point_stored_points__stored_points_id__point__point_id__file__file_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/project-tags/": {
      "get": {
        "tags": ["Project Tags"],
        "summary": "Get all project_tags - Sodex only",
        "description": "Get all project_tags",
        "operationId": "get_all_project_tags_project_tags__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/project-tags/{project_tag_id}": {
      "get": {
        "tags": ["Project Tags"],
        "summary": "Get project_tag by id",
        "description": "Get project_tag by id",
        "operationId": "get_project_tag_by_id_project_tags__project_tag_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["Project Tags"],
        "summary": "Update project_tag",
        "description": "Update project_tag",
        "operationId": "update_project_tag_project_tags__project_tag_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Project Tags"],
        "summary": "Delete project_tag",
        "description": "Delete project_tag",
        "operationId": "delete_project_tag_project_tags__project_tag_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/project-tags": {
      "get": {
        "tags": ["Project Tags"],
        "summary": "Get project project_tags",
        "description": "Get project project_tags",
        "operationId": "get_project_project_tags_projects__project_id__project_tags_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Project Tags"],
        "summary": "Create project project_tag",
        "description": "Create project project_tag",
        "operationId": "create_project_project_tag_projects__project_id__project_tags_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshot-comparisons/": {
      "get": {
        "tags": ["Snapshotcomparison"],
        "summary": "Get all SnapshotComparisons - Sodex only",
        "description": "Get all SnapshotComparisons",
        "operationId": "get_all_snapshot_comparisons_snapshot_comparisons__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/snapshot-comparisons": {
      "get": {
        "tags": ["Snapshotcomparison"],
        "summary": "Get Project SnapshotComparisons",
        "description": "Get Project SnapshotComparisons",
        "operationId": "get_project_snapshot_comparisons_projects__project_id__snapshot_comparisons_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Snapshotcomparison"],
        "summary": "Create Project SnapshotComparison",
        "description": "Create Project SnapshotComparison",
        "operationId": "create_project_snapshot_comparison_projects__project_id__snapshot_comparisons_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshot-comparisons/{snapshot_comparison_id}": {
      "get": {
        "tags": ["Snapshotcomparison"],
        "summary": "Get SnapshotComparison by id",
        "description": "Get SnapshotComparison by id",
        "operationId": "get_snapshot_comparison_by_id_snapshot_comparisons__snapshot_comparison_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Snapshotcomparison"],
        "summary": "Update SnapshotComparison",
        "description": "Update SnapshotComparison",
        "operationId": "update_snapshot_comparison_snapshot_comparisons__snapshot_comparison_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Snapshotcomparison"],
        "summary": "Delete SnapshotComparison",
        "description": "Delete SnapshotComparison",
        "operationId": "delete_snapshot_comparison_snapshot_comparisons__snapshot_comparison_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/gcp-sets/": {
      "get": {
        "tags": ["GCP Sets"],
        "summary": "Get all gcp_sets - Sodex only",
        "description": "Get all gcp_sets",
        "operationId": "get_all_gcp_sets_gcp_sets__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/gcp-sets/{gcp_set_id}": {
      "get": {
        "tags": ["GCP Sets"],
        "summary": "Get gcp_set by id",
        "description": "Get gcp_set by id",
        "operationId": "get_gcp_set_by_id_gcp_sets__gcp_set_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      },
      "put": {
        "tags": ["GCP Sets"],
        "summary": "Update gcp_set",
        "description": "Update gcp_set",
        "operationId": "update_gcp_set_gcp_sets__gcp_set_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["GCP Sets"],
        "summary": "Delete gcp_set",
        "description": "Delete gcp_set",
        "operationId": "delete_gcp_set_gcp_sets__gcp_set_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/projects/{project_id}/gcp-sets": {
      "get": {
        "tags": ["GCP Sets"],
        "summary": "Get project gcp_sets",
        "description": "Get project gcp_sets",
        "operationId": "get_project_gcp_sets_projects__project_id__gcp_sets_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["GCP Sets"],
        "summary": "Create project gcp_set",
        "description": "Create project gcp_set",
        "operationId": "create_project_gcp_set_projects__project_id__gcp_sets_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/pending-jobs/": {
      "get": {
        "tags": ["PendingJobs"],
        "summary": "Get all PendingJobs - Sodex only",
        "description": "Get all PendingJobs",
        "operationId": "get_all_pending_jobs_pending_jobs__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/organizations/me/pending-jobs": {
      "get": {
        "tags": ["PendingJobs"],
        "summary": "Get my organization PendingJobs",
        "description": "Get my organization PendingJobs",
        "operationId": "get_my_organization_pending_jobs_organizations_me_pending_jobs_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/pending-jobs": {
      "get": {
        "tags": ["PendingJobs"],
        "summary": "Get organization PendingJobs",
        "description": "Get organization PendingJobs",
        "operationId": "get_organization_pending_jobs_organizations__organization_id__pending_jobs_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/pending-jobs": {
      "get": {
        "tags": ["PendingJobs"],
        "summary": "Get Project PendingJobs",
        "description": "Get Project PendingJobs",
        "operationId": "get_project_pending_jobs_projects__project_id__pending_jobs_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["PendingJobs"],
        "summary": "Create PendingJob",
        "description": "Create PendingJob",
        "operationId": "create_pending_job_projects__project_id__pending_jobs_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/pending-jobs/{pending_job_id}": {
      "get": {
        "tags": ["PendingJobs"],
        "summary": "Get PendingJob by id",
        "description": "Get PendingJob by id",
        "operationId": "get_pending_job_by_id_pending_jobs__pending_job_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["PendingJobs"],
        "summary": "Update PendingJob",
        "description": "Update PendingJob",
        "operationId": "update_pending_job_pending_jobs__pending_job_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["PendingJobs"],
        "summary": "Delete PendingJob",
        "description": "Delete PendingJob",
        "operationId": "delete_pending_job_pending_jobs__pending_job_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/pending-jobs/{pending_job_id}/execute": {
      "post": {
        "tags": ["PendingJobs"],
        "summary": "Execute PendingJob",
        "description": "Execute PendingJob",
        "operationId": "execute_pending_job_pending_jobs__pending_job_id__execute_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/autostart-geofences/": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get all AutostartGeofences - Sodex only",
        "description": "Get all AutostartGeofences",
        "operationId": "get_all_autostart_geofences_autostart_geofences__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/organizations/me/autostart-geofences": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get my organization AutostartGeofences",
        "description": "Get my organization AutostartGeofences",
        "operationId": "get_my_organization_autostart_geofences_organizations_me_autostart_geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/autostart-geofences": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get organization AutostartGeofences",
        "description": "Get organization AutostartGeofences",
        "operationId": "get_organization_autostart_geofences_organizations__organization_id__autostart_geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/autostart-geofences": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get Project AutostartGeofences",
        "description": "Get Project AutostartGeofences",
        "operationId": "get_project_autostart_geofences_projects__project_id__autostart_geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Autostartgeofence"],
        "summary": "Create Project AutostartGeofence",
        "description": "Create Project AutostartGeofence",
        "operationId": "create_project_autostart_geofence_projects__project_id__autostart_geofences_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/autostart-geofence": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get Project AutostartGeofence",
        "description": "Get Project AutostartGeofence",
        "operationId": "get_project_autostart_geofence_projects__project_id__autostart_geofence_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/autostart-geofences": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get my system AutostartGeofences",
        "description": "Get my system AutostartGeofences",
        "operationId": "get_my_system_autostart_geofences_systems_me_autostart_geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/autostart-geofences": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get System AutostartGeofences",
        "description": "Get System AutostartGeofences",
        "operationId": "get_system_autostart_geofences_systems__system_id__autostart_geofences_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          }
        ]
      }
    },
    "/autostart-geofences/{autostart_geofence_id}": {
      "get": {
        "tags": ["Autostartgeofence"],
        "summary": "Get AutostartGeofence by id",
        "description": "Get AutostartGeofence by id",
        "operationId": "get_autostart_geofence_by_id_autostart_geofences__autostart_geofence_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Autostartgeofence"],
        "summary": "Update AutostartGeofence",
        "description": "Update AutostartGeofence",
        "operationId": "update_autostart_geofence_autostart_geofences__autostart_geofence_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Autostartgeofence"],
        "summary": "Delete AutostartGeofence",
        "description": "Delete AutostartGeofence",
        "operationId": "delete_autostart_geofence_autostart_geofences__autostart_geofence_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/autostart-geofences/{autostart_geofence_id}/update-check": {
      "post": {
        "tags": ["Autostartgeofence"],
        "summary": "Check Update AutostartGeofence",
        "description": "Check Update AutostartGeofence geofence coordinates",
        "operationId": "check_update_autostart_geofence_autostart_geofences__autostart_geofence_id__update_check_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/autostart-geofences/{autostart_geofence_id}/system-add-check": {
      "post": {
        "tags": ["Autostartgeofence"],
        "summary": "Check AutostartGeofence system add",
        "description": "Check AutostartGeofence system add",
        "operationId": "check_autostart_geofence_system_add_autostart_geofences__autostart_geofence_id__system_add_check_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/measurements/": {
      "get": {
        "tags": ["Layered Measurements"],
        "summary": "Get all Measurements - Sodex only",
        "description": "Get all Measurements",
        "operationId": "get_all_measurements_measurements__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/organizations/me/measurements": {
      "get": {
        "tags": ["Layered Measurements"],
        "summary": "Get my organization Measurements",
        "description": "Get my organization Measurements",
        "operationId": "get_my_organization_measurements_organizations_me_measurements_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/measurements": {
      "get": {
        "tags": ["Layered Measurements"],
        "summary": "Get organization Measurements",
        "description": "Get organization Measurements",
        "operationId": "get_organization_measurements_organizations__organization_id__measurements_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/measurements": {
      "get": {
        "tags": ["Layered Measurements"],
        "summary": "Get Project Measurements",
        "description": "Get Project Measurements",
        "operationId": "get_project_measurements_projects__project_id__measurements_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Layered Measurements"],
        "summary": "Create Project Measurement",
        "description": "Create Project Measurement",
        "operationId": "create_project_measurement_projects__project_id__measurements_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/measurement-layers/{measurement_layer_id}/measurements": {
      "get": {
        "tags": ["Layered Measurements"],
        "summary": "Get Measurement Layer Measurements",
        "description": "Get Measurement Layer Measurements",
        "operationId": "get_measurement_layer_measurements_measurement_layers__measurement_layer_id__measurements_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/measurements/{measurement_id}": {
      "get": {
        "tags": ["Layered Measurements"],
        "summary": "Get Measurement by id",
        "description": "Get Measurement by id",
        "operationId": "get_measurement_by_id_measurements__measurement_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Layered Measurements"],
        "summary": "Update Measurement",
        "description": "Update Measurement",
        "operationId": "update_measurement_measurements__measurement_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Layered Measurements"],
        "summary": "Delete Measurement",
        "description": "Delete Measurement",
        "operationId": "delete_measurement_measurements__measurement_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshots/{snapshot_id}/measurements/telekom-transfer": {
      "post": {
        "tags": ["Layered Measurements"],
        "summary": "Transfer Measurements to Telekom",
        "description": "Transfer Measurements to Telekom",
        "operationId": "transfer_measurements_to_telekom_snapshots__snapshot_id__measurements_telekom_transfer_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/measurement-layers/": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get all MeasurementLayers - Sodex only",
        "description": "Get all MeasurementLayers",
        "operationId": "get_all_measurement_layers_measurement_layers__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/organizations/me/measurement-layers": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get my organization MeasurementLayers",
        "description": "Get my organization MeasurementLayers",
        "operationId": "get_my_organization_measurement_layers_organizations_me_measurement_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/measurement-layers": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get organization MeasurementLayers",
        "description": "Get organization MeasurementLayers",
        "operationId": "get_organization_measurement_layers_organizations__organization_id__measurement_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/measurement-layers": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get Project MeasurementLayers",
        "description": "Get Project MeasurementLayers",
        "operationId": "get_project_measurement_layers_projects__project_id__measurement_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["Measurementlayers"],
        "summary": "Create Project MeasurementLayer",
        "description": "Create Project MeasurementLayer",
        "operationId": "create_project_measurement_layer_projects__project_id__measurement_layers_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/measurement-layers/{measurement_layer_id}/measurement-layers": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get Parent MeasurementLayers",
        "description": "Get Parent MeasurementLayers",
        "operationId": "get_parent_measurement_layers_measurement_layers__measurement_layer_id__measurement_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/snapshots/{snapshot_id}/measurement-layers": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get Snapshot MeasurementLayers",
        "description": "Get Snapshot MeasurementLayers",
        "operationId": "get_snapshot_measurement_layers_snapshots__snapshot_id__measurement_layers_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/measurement-layers/{measurement_layer_id}": {
      "get": {
        "tags": ["Measurementlayers"],
        "summary": "Get MeasurementLayer by id",
        "description": "Get MeasurementLayer by id",
        "operationId": "get_measurement_layer_by_id_measurement_layers__measurement_layer_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["Measurementlayers"],
        "summary": "Update MeasurementLayer",
        "description": "Update MeasurementLayer",
        "operationId": "update_measurement_layer_measurement_layers__measurement_layer_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["Measurementlayers"],
        "summary": "Delete MeasurementLayer",
        "description": "Delete MeasurementLayer",
        "operationId": "delete_measurement_layer_measurement_layers__measurement_layer_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/2d-plans/": {
      "get": {
        "tags": ["2D Plans"],
        "summary": "Get all 2DPlans - Sodex only",
        "description": "Get all 2DPlans",
        "operationId": "get_all_2d_plans_2d_plans__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["sodex"]
          }
        ]
      }
    },
    "/organizations/me/2d-plans": {
      "get": {
        "tags": ["2D Plans"],
        "summary": "Get my organization 2DPlans",
        "description": "Get my organization 2DPlans",
        "operationId": "get_my_organization_2d_plans_organizations_me_2d_plans_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/organizations/{organization_id}/2d-plans": {
      "get": {
        "tags": ["2D Plans"],
        "summary": "Get organization 2DPlans",
        "description": "Get organization 2DPlans",
        "operationId": "get_organization_plan_2ds_organizations__organization_id__2d_plans_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/projects/{project_id}/2d-plans": {
      "get": {
        "tags": ["2D Plans"],
        "summary": "Get Project 2DPlans",
        "description": "Get Project 2DPlans",
        "operationId": "get_project_2d_plans_projects__project_id__2d_plans_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["2D Plans"],
        "summary": "Create Project 2DPlan",
        "description": "Create Project 2DPlan",
        "operationId": "create_project_2d_plan_projects__project_id__2d_plans_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/2d-plans/{plan_2d_id}": {
      "get": {
        "tags": ["2D Plans"],
        "summary": "Get 2DPlan by id",
        "description": "Get 2DPlan by id",
        "operationId": "get_2d_plan_by_id_2d_plans__plan_2d_id__get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "guest", "sodex"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["2D Plans"],
        "summary": "Update 2DPlan",
        "description": "Update 2DPlan",
        "operationId": "update_2d_plan_2d_plans__plan_2d_id__put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "delete": {
        "tags": ["2D Plans"],
        "summary": "Delete 2DPlan",
        "description": "Delete 2DPlan",
        "operationId": "delete_2d_plan_2d_plans__plan_2d_id__delete",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/2d-plans/{plan_2d_id}/geojson": {
      "get": {
        "tags": ["2D Plans"],
        "summary": "Get 2DPlan GeoJSON",
        "description": "Get 2DPlan GeoJSON",
        "operationId": "get_2d_plan_geojson_2d_plans__plan_2d_id__geojson_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base", "system", "guest"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/users/me/projects/{project_id}/project-notification-type-setting": {
      "put": {
        "tags": ["ProjectNotificationSettings"],
        "summary": "Update user project notification type setting",
        "description": "Update user project notification type setting",
        "operationId": "update_user_project_notification_type_setting_users_me_projects__project_id__project_notification_type_setting_put",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/users/me/projects/{project_id}/project-notification-type-settings": {
      "get": {
        "tags": ["ProjectNotificationSettings"],
        "summary": "Get user project notification type settings",
        "description": "Get user project notification type settings",
        "operationId": "get_user_project_notification_type_settings_users_me_projects__project_id__project_notification_type_settings_get",
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/projects/{project_id}/uhf-configurations": {
      "get": {
        "tags": ["UHF Configurations"],
        "summary": "Get My System Project UhfConfigurations",
        "description": "Get My System Project UhfConfigurations",
        "operationId": "get_my_system_project_uhf_configurations_systems_me_projects__project_id__uhf_configurations_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/projects/{project_id}/uhf-configurations": {
      "get": {
        "tags": ["UHF Configurations"],
        "summary": "Get System Project UhfConfigurations",
        "description": "Get System Project UhfConfigurations",
        "operationId": "get_system_project_uhf_configurations_systems__system_id__projects__project_id__uhf_configurations_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/uhf-configurations": {
      "get": {
        "tags": ["UHF Configurations"],
        "summary": "Get My System UhfConfigurations",
        "description": "Get My System UhfConfigurations",
        "operationId": "get_my_system_uhf_configurations_systems_me_uhf_configurations_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/me/uhf-configurations/default": {
      "get": {
        "tags": ["UHF Configurations"],
        "summary": "Get My System Default UhfConfiguration",
        "description": "Get My System Default UhfConfiguration",
        "operationId": "get_my_system_default_uhf_configuration_systems_me_uhf_configurations_default_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "put": {
        "tags": ["UHF Configurations"],
        "summary": "Update My System Default UhfConfiguration",
        "description": "Update My System Default UhfConfiguration",
        "operationId": "update_my_uhf_configuration_systems_me_uhf_configurations_default_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["system"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/uhf-configurations/default": {
      "get": {
        "tags": ["UHF Configurations"],
        "summary": "Get System Default UhfConfiguration",
        "description": "Get System Default UhfConfiguration",
        "operationId": "get_system_default_uhf_configuration_systems__system_id__uhf_configurations_default_get",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          }
        ]
      },
      "put": {
        "tags": ["UHF Configurations"],
        "summary": "Update System Default UhfConfiguration",
        "description": "Update System Default UhfConfiguration",
        "operationId": "update_system_default_uhf_configuration_systems__system_id__uhf_configurations_default_put",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": ["system_admin"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      },
      "post": {
        "tags": ["UHF Configurations"],
        "summary": "Create System Default UhfConfiguration",
        "description": "Create System Default UhfConfiguration",
        "operationId": "create_system_default_uhf_configuration_systems__system_id__uhf_configurations_default_post",
        "security": [
          {
            "OAuth2PasswordBearer": ["cloud_base"]
          },
          {
            "OAuth2PasswordBearer": ["system_admin"]
          },
          {
            "OAuth2PasswordBearer": []
          }
        ]
      }
    },
    "/systems/{system_id}/uhf-configurations": {
      "get": {
        "tags": ["UHF Configurations"],
        "summary": "Get System UhfConfigurations",
        "description": "Get System UhfConfigurations",
        "operationId": "get_system_uhf_configurations_systems__system_id__uhf_configurations_get",
        "security": [
          {
[...]
